### ISSUE TITLE
Client crash when exiting to Main Menu

### ISSUE THREAD

**Issue by Machine-Maker** [klyte45/ElectricRoads#2] opened 2019-06-03 20:36 UTC
When I click exit game and select the main menu option, the game crashes. Attached is the output_log.txt for the crash
[output_log.txt](https://github.com/klyte45/ElectricRoads/files/3249388/output_log.txt)

**Comment by klyte45** [comment] 2019-07-14 21:09
This is an expected behavior since not doing this can corrupt the savegame.
Won't fix

**Closed by klyte45** 2019-07-14 21:09 UTC
